name: Discord Bot Schedule Messages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'   # 00:00 giờ Việt Nam
    - cron: '0 0 * * *'    # 07:00 giờ Việt Nam
    - cron: '0 1 * * *'    # 08:00 giờ Việt Nam, chỉ gửi vào ngày đặc biệt
    - cron: '0 5 * * *'    # 12:00 giờ Việt Nam
jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        npm install
        npm install pm2@latest -g

    - name: Create env file
      run: |
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_BOT_KEY }}" > .env
        echo "CHANNEL_ID=${{ secrets.CHANNEL_ID }}" >> .env

    - name: Run Bot
      run: node run-scheduled.js
