name: Discord Bot Schedule Messages

on:
  schedule:
    - cron: '45 22 * * *'  # Chạy lúc 6:45 UTC+7 (đêm)
    - cron: '45 16 * * *'  # Chạy lúc 22:45 UTC+7 (sáng)
    - cron: '45 4 * * *'     # 11:45 VN
jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        npm install
        npm install pm2@latest -g

    - name: Create env file
      run: |
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
        echo "CHANNEL_ID=${{ secrets.CHANNEL_ID }}" >> .env

    - name: Run Bot
      run: node run-scheduled.js
